name: liga_vi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py39h06a4308_0
  - cycler=0.10.0=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.0=h5202010_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py39h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.4.2=py39h06a4308_0
  - matplotlib-base=3.4.2=py39hab158f2_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.2=he6710b0_1
  - olefile=0.46=py_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h27cfd23_0
  - pcre=8.45=h295c915_0
  - pillow=8.3.1=py39h2c7a002_0
  - pip=21.2.2=py39h06a4308_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - python=3.9.6=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py39h27cfd23_0
  - tzdata=2021a=h52ac0ba_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.13.0
    - astunparse==1.6.3
    - cachetools==4.2.2
    - cdt==0.5.23
    - charset-normalizer==2.0.4
    - chex==0.0.8
    - click==8.0.1
    - cloudpickle==1.6.0
    - configparser==5.0.2
    - cython==0.29.24
    - decorator==5.0.9
    - dm-haiku==0.0.4
    - dm-tree==0.1.6
    - docker-pycreds==0.4.0
    - flatbuffers==1.12
    - fuzzywuzzy==0.18.0
    - gast==0.4.0
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.34.0
    - google-auth-oauthlib==0.4.5
    - google-pasta==0.2.0
    - gputil==1.4.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==3.2
    - jax==0.2.18
    - jaxlib==0.1.69+cuda111
    - joblib==1.0.1
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - lingam==1.5.4
    - markdown==3.3.4
    - networkx==2.6.2
    - numpy==1.20.0
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - optax==0.0.9
    - ott-jax==0.1.14
    - pandas==1.3.1
    - pathtools==0.1.2
    - patsy==0.5.1
    - promise==2.3
    - protobuf==3.17.3
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-graphviz==0.17
    - python-levenshtein==0.12.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - sentry-sdk==1.3.1
    - shortuuid==1.0.1
    - six==1.15.0
    - skrebate==0.62
    - smmap==4.0.0
    - statsmodels==0.12.2
    - subprocess32==3.5.4
    - sumu==0.1.2
    - tabulate==0.8.9
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - tensorflow-probability==0.13.0
    - termcolor==1.1.0
    - threadpoolctl==2.2.0
    - toolz==0.11.1
    - torch==1.9.0
    - tqdm==4.62.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - wandb==0.11.2
    - werkzeug==2.0.1
    - wrapt==1.12.1
prefix: liga_vi

